spring:
  application:
    # 应用名
    name: network-mall
--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://aws.gedune.space:23306/shop_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Gedune150.
  # 邮箱配置
  mail:
    host: smtp.163.com
    port: 587
    username: gedune123@163.com
    password: APJBVMBRGLDIWCEB
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# XXL-JOB 配置
# xxl:
#   job:
#     # 是否开启 XXL-JOB：true-开启 false-不开启
#     enabled: false
#     admin:
#       ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#       addresses: http://127.0.0.1:8080/xxl-job-admin
#     executor:
#       ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#       appname: xxl-job-executor-novel
#       ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#       logpath: logs/xxl-job/jobhandler
#     ### xxl-job, access token
#     accessToken: 123

--- #----------------------安全配置----------------------------
# spring:
#   # Spring Boot 应用管理和监控
#   boot:
#     admin:
#       client:
#         # 是否开启 Spring Boot Admin 客户端
#         enabled: false
#         # Spring Boot Admin 服务端注册地址
#         url: http://localhost:8080
#         # Spring Boot Admin 服务端认证用户名
#         username: novel
#         # Spring Boot Admin 服务端认证密码
#         password: novel
#         instance:
#           metadata:
#             # SBA Client
#             user.name: ${spring.security.user.name}
#             user.password: ${spring.security.user.password}
#   security:
#     user:
#       name: ENDPOINT_ADMIN
#       password: ENDPOINT_ADMIN
#       roles: ENDPOINT_ADMIN
--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: true
--- #----------------------邮箱配置-----------------------------
#邮箱服务器
# spring:
#   mail:
#     host: smtp.163.com
#     #发件人昵称
#     nickname: xxyopen
#     #邮箱账户
#     username: xxx@163.com
#     #邮箱第三方授权码
#     password: xxx
#     #编码类型
#     default-encoding: UTF-8
#     port: 465
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#             required: rue
#           socketFactory:
#             port: 465
#             class: javax.net.ssl.SSLSocketFactory
#             fallback: false
